--------------------------------------------------------
--  Constraints for Table ADDEVICECONTAINER
--------------------------------------------------------

  ALTER TABLE "SEN11CP2MSI164"."ADDEVICECONTAINER" MODIFY ("DEVICENAME" NOT NULL ENABLE);
  ALTER TABLE "SEN11CP2MSI164"."ADDEVICECONTAINER" MODIFY ("CONTAINER" NOT NULL ENABLE);
  ALTER TABLE "SEN11CP2MSI164"."ADDEVICECONTAINER" MODIFY ("DISTINGUISHEDNAME" NOT NULL ENABLE);
  ALTER TABLE "SEN11CP2MSI164"."ADDEVICECONTAINER" ADD PRIMARY KEY ("DEVICENAME", "CONTAINER")
  USING INDEX  ENABLE;
