--------------------------------------------------------
--  DDL for Table ADINFO
--------------------------------------------------------

  CREATE TABLE "SEN11CP2MSI164"."ADINFO" 
   (	"DEVICE_ID" NVARCHAR2(50), 
	"CTIME" DATE, 
	"MTIME" DATE, 
	"COMPDN" NVARCHAR2(255), 
	"COMPDOMN" NVARCHAR2(128), 
	"COMPGUID" NVARCHAR2(128), 
	"COMPNAME" NVARCHAR2(128), 
	"COMPSITE" NVARCHAR2(128), 
	"COMPUPN" NVARCHAR2(128), 
	"USERDN" NVARCHAR2(128), 
	"USERDOMN" NVARCHAR2(128), 
	"USERGUID" NVARCHAR2(128), 
	"USERNAME" NVARCHAR2(128), 
	"USERUPN" NVARCHAR2(128), 
	"RMADEVDN" NVARCHAR2(128)
   ) ;
