--------------------------------------------------------
--  DDL for Table APPEVENT
--------------------------------------------------------

  CREATE TABLE "SEN11CP2MSI164"."APPEVENT" 
   (	"DEVICE_ID" NVARCHAR2(50), 
	"CTIME" DATE, 
	"MTIME" DATE, 
	"SERVICE_ID" NVARCHAR2(50), 
	"PRODUCT" NVARCHAR2(10), 
	"APP_NAME" NVARCHAR2(80), 
	"CATGROUP" NVARCHAR2(128), 
	"ERRORNUM" NVARCHAR2(10), 
	"EVENT" NVARCHAR2(20), 
	"STATUS" NVARCHAR2(255), 
	"DEL_TIME" NVARCHAR2(30), 
	"VER_TIME" NVARCHAR2(30), 
	"INST_TIME" NVARCHAR2(30), 
	"FIX_TIME" NVARCHAR2(30), 
	"DOWNL_TIME" NVARCHAR2(30), 
	"NVD_DOMAIN" NVARCHAR2(32), 
	"NVD_CLASS" NVARCHAR2(15), 
	"JOBID" NVARCHAR2(64), 
	"CJOBID" NVARCHAR2(64)
   ) ;
