--------------------------------------------------------
--  DDL for Table APPRNPEVENT
--------------------------------------------------------

  CREATE TABLE "SEN11CP2MSI164"."APPRNPEVENT" 
   (	"DEVICE_ID" NVARCHAR2(50), 
	"CTIME" DATE, 
	"MTIME" DATE, 
	"CJOBID" NVARCHAR2(50), 
	"CMDMSG" NVARCHAR2(255), 
	"CMDRC" NUMBER(*,0), 
	"EVENT" NVARCHAR2(50), 
	"INSTDATE" NVARCHAR2(30), 
	"JOBID" NVARCHAR2(50), 
	"MODULE" NVARCHAR2(255), 
	"POSTMSG" NVARCHAR2(255), 
	"POSTRC" NUMBER(*,0), 
	"ZOBJCLAS" NVARCHAR2(25), 
	"ZOBJDATE" NVARCHAR2(25), 
	"ZOBJDOMN" NVARCHAR2(25), 
	"ZOBJID" NVARCHAR2(50), 
	"ZOBJNAME" NVARCHAR2(50), 
	"ZOBJTIME" NVARCHAR2(20), 
	"ZSVCNAME" NVARCHAR2(255), 
	"ZUSERID" NVARCHAR2(50)
   ) ;
