--------------------------------------------------------
--  Constraints for Table APPV_SERVICES
--------------------------------------------------------

  ALTER TABLE "SEN11CP2MSI164"."APPV_SERVICES" MODIFY ("SERVICES_KEY" NOT NULL ENABLE);
  ALTER TABLE "SEN11CP2MSI164"."APPV_SERVICES" MODIFY ("SERVICE_ID" NOT NULL ENABLE);
  ALTER TABLE "SEN11CP2MSI164"."APPV_SERVICES" ADD PRIMARY KEY ("SERVICES_KEY")
  USING INDEX  ENABLE;
  ALTER TABLE "SEN11CP2MSI164"."APPV_SERVICES" ADD CONSTRAINT "UKKB29SSDO7B84OFOPMCG6KAU2J" UNIQUE ("SERVICE_ID")
  USING INDEX  ENABLE;
