--------------------------------------------------------
--  DDL for Table AUTOPILOT_DEVICEMGMT
--------------------------------------------------------

  CREATE TABLE "SEN11CP2MSI164"."AUTOPILOT_DEVICEMGMT" 
   (	"DEVICE_ID" NVARCHAR2(50), 
	"DEVICE_NAME" NVARCHAR2(50), 
	"BOOT_AGENT_INSTALL_TIME" DATE, 
	"BOOT_AGENT_RUNNING_STATUS" NVARCHAR2(100), 
	"RADIA_AGENT_INSTALL_TIME" DATE, 
	"RADIA_AGENT_RUNNING_STATUS" NVARCHAR2(100), 
	"MDM_ENROLLMENT_STATUS" NVARCHAR2(50), 
	"LAST_UPDATE" DATE
   ) ;
