--------------------------------------------------------
--  DDL for Table COBSTATS
--------------------------------------------------------

  CREATE TABLE "SEN11CP2MSI164"."COBSTATS" 
   (	"DEVICE_ID" NVARCHAR2(50), 
	"SYNCSTATUS" NVARCHAR2(50), 
	"SERVERTYPE" NVARCHAR2(10), 
	"SERVERHOST" NVARCHAR2(100), 
	"SERVERPORT" NUMBER(*,0), 
	"SERVERSTARTTIME" DATE, 
	"SERVERENDTIME" DATE, 
	"MTIME" DATE, 
	"MYSQLSTARTTIME" DATE, 
	"OPENLDAPSTARTTIME" DATE, 
	"CSDBSTARTTIME" DATE, 
	"JOBSSTARTTIME" DATE, 
	"MYSQLENDTIME" DATE, 
	"OPENLDAPENDTIME" DATE, 
	"CSDBENDTIME" DATE, 
	"JOBSENDTIME" DATE, 
	"MYSQLSTATUS" NVARCHAR2(50), 
	"OPENLDAPSTATUS" NVARCHAR2(50), 
	"CSDBSTATUS" NVARCHAR2(50), 
	"JOBSSTATUS" NVARCHAR2(50), 
	"MYSQLSIZE" NUMBER(*,0), 
	"OPENLDAPSIZE" NUMBER(*,0), 
	"CSDBSIZE" NUMBER(*,0), 
	"JOBSSIZE" NUMBER(*,0), 
	"MYSQLSTATUSMESSAGE" NVARCHAR2(100), 
	"OPENLDAPSTATUSMESSAGE" NVARCHAR2(100), 
	"CSDBSTATUSMESSAGE" NVARCHAR2(100), 
	"JOBSSTATUSMESSAGE" NVARCHAR2(100)
   ) ;
