--------------------------------------------------------
--  DDL for Table NETDEVICETEMPCONFIG
--------------------------------------------------------

  CREATE TABLE "SEN11CP2MSI164"."NETDEVICETEMPCONFIG" 
   (	"STATUS" NVARCHAR2(50), 
	"DEVICE_ID" NVARCHAR2(50), 
	"MTIME" DATE, 
	"DEVICETYPE" NVARCHAR2(128), 
	"IPADDR" NVARCHAR2(128), 
	"OS" NVARCHAR2(128), 
	"OS_LEVEL" NVARCHAR2(128), 
	"SUBNETADDR" NVARCHAR2(128), 
	"SUBNETRANGE" NVARCHAR2(128), 
	"MACADDR" NVARCHAR2(128), 
	"SLNO" NVARCHAR2(128), 
	"DOMAIN" NVARCHAR2(128), 
	"WORKGROUP" NVARCHAR2(128), 
	"MODEL" NVARCHAR2(128), 
	"NETBIOS" NVARCHAR2(128), 
	"DCLASS" NVARCHAR2(128), 
	"MANUFACTURER" NVARCHAR2(128)
   ) ;
