--------------------------------------------------------
--  Constraints for Table NVD_PUBERROR
--------------------------------------------------------

  ALTER TABLE "SEN11CP2MSI164"."NVD_PUBERROR" MODIFY ("NVD_ZOBJNAME" NOT NULL ENABLE);
  ALTER TABLE "SEN11CP2MSI164"."NVD_PUBERROR" MODIFY ("NVD_ZOBJDATE" NOT NULL ENABLE);
  ALTER TABLE "SEN11CP2MSI164"."NVD_PUBERROR" MODIFY ("NVD_ZOBJTIME" NOT NULL ENABLE);
  ALTER TABLE "SEN11CP2MSI164"."NVD_PUBERROR" ADD PRIMARY KEY ("NVD_ZOBJNAME")
  USING INDEX  ENABLE;
