--------------------------------------------------------
--  Constraints for Table NVD_FILECHG
--------------------------------------------------------

  ALTER TABLE "SEN11CP2MSI164"."NVD_FILECHG" MODIFY ("NVD_ZOBJNAME" NOT NULL ENABLE);
  ALTER TABLE "SEN11CP2MSI164"."NVD_FILECHG" MODIFY ("NVD_ZOBJDATE" NOT NULL ENABLE);
  ALTER TABLE "SEN11CP2MSI164"."NVD_FILECHG" MODIFY ("NVD_ZOBJTIME" NOT NULL ENABLE);
  ALTER TABLE "SEN11CP2MSI164"."NVD_FILECHG" ADD PRIMARY KEY ("NVD_ZOBJNAME")
  USING INDEX  ENABLE;
