--------------------------------------------------------
--  DDL for Table NVD_PATCHSIG
--------------------------------------------------------

  CREATE TABLE "SEN11CP2MSI164"."NVD_PATCHSIG" 
   (	"NVD_ZOBJNAME" NVARCHAR2(32), 
	"NVD_ZOBJDATE" NVARCHAR2(8), 
	"NVD_ZOBJTIME" NVARCHAR2(8), 
	"NVD_ZOBJRCRC" NVARCHAR2(8), 
	"NVD_ZOBJID" NVARCHAR2(12), 
	"NVD_ZUNUSED1" NVARCHAR2(4), 
	"NVD_ZOBJCID" NVARCHAR2(12), 
	"NVD_ZOBJRSIZ" NVARCHAR2(8), 
	"NVD_ZSTOP001" NVARCHAR2(255), 
	"NVD_NAME" NVARCHAR2(32), 
	"NVD_ID" NVARCHAR2(12), 
	"NVD_CRC" NVARCHAR2(8), 
	"NVD_CTIME" NVARCHAR2(24), 
	"NVD_MTIME" NVARCHAR2(24)
   ) ;
