--------------------------------------------------------
--  Constraints for Table NVD_PASTATUS
--------------------------------------------------------

  ALTER TABLE "SEN11CP2MSI164"."NVD_PASTATUS" MODIFY ("NVD_ZOBJDEV" NOT NULL ENABLE);
  ALTER TABLE "SEN11CP2MSI164"."NVD_PASTATUS" MODIFY ("NVD_ZOBJNAME" NOT NULL ENABLE);
  ALTER TABLE "SEN11CP2MSI164"."NVD_PASTATUS" MODIFY ("NVD_ZOBJRC" NOT NULL ENABLE);
  ALTER TABLE "SEN11CP2MSI164"."NVD_PASTATUS" ADD PRIMARY KEY ("NVD_ZOBJDEV", "NVD_ZOBJNAME")
  USING INDEX  ENABLE;
