--------------------------------------------------------
--  Constraints for Table NVD_PATCHSIG
--------------------------------------------------------

  ALTER TABLE "SEN11CP2MSI164"."NVD_PATCHSIG" MODIFY ("NVD_ZOBJNAME" NOT NULL ENABLE);
  ALTER TABLE "SEN11CP2MSI164"."NVD_PATCHSIG" MODIFY ("NVD_ZOBJDATE" NOT NULL ENABLE);
  ALTER TABLE "SEN11CP2MSI164"."NVD_PATCHSIG" MODIFY ("NVD_ZOBJTIME" NOT NULL ENABLE);
  ALTER TABLE "SEN11CP2MSI164"."NVD_PATCHSIG" ADD PRIMARY KEY ("NVD_ZOBJNAME")
  USING INDEX  ENABLE;
