--------------------------------------------------------
--  Constraints for Table NVD_LOCATION
--------------------------------------------------------

  ALTER TABLE "SEN11CP2MSI164"."NVD_LOCATION" MODIFY ("NVD_ZOBJNAME" NOT NULL ENABLE);
  ALTER TABLE "SEN11CP2MSI164"."NVD_LOCATION" MODIFY ("NVD_ZOBJDATE" NOT NULL ENABLE);
  ALTER TABLE "SEN11CP2MSI164"."NVD_LOCATION" MODIFY ("NVD_ZOBJTIME" NOT NULL ENABLE);
  ALTER TABLE "SEN11CP2MSI164"."NVD_LOCATION" ADD PRIMARY KEY ("NVD_ZOBJNAME")
  USING INDEX  ENABLE;
