--------------------------------------------------------
--  DDL for Table NVD_FILECHG
--------------------------------------------------------

  CREATE TABLE "SEN11CP2MSI164"."NVD_FILECHG" 
   (	"NVD_ZOBJNAME" NVARCHAR2(32), 
	"NVD_ZOBJDATE" NVARCHAR2(8), 
	"NVD_ZOBJTIME" NVARCHAR2(8), 
	"NVD_ZOBJRCRC" NVARCHAR2(8), 
	"NVD_ZOBJID" NVARCHAR2(12), 
	"NVD_ZUNUSED1" NVARCHAR2(4), 
	"NVD_ZOBJCID" NVARCHAR2(12), 
	"NVD_ZOBJRSIZ" NVARCHAR2(8), 
	"NVD_PATH" NVARCHAR2(255), 
	"NVD_NAME" NVARCHAR2(255), 
	"NVD_VERSION" NVARCHAR2(32), 
	"NVD_GMTDATE" NVARCHAR2(8), 
	"NVD_GMTTIME" NVARCHAR2(8), 
	"NVD_CHECKSUM" NVARCHAR2(12), 
	"NVD_CRC32" NVARCHAR2(12), 
	"NVD_SIZE" NVARCHAR2(12), 
	"NVD_ZOBJPART" NVARCHAR2(128), 
	"NVD_REPORT" NVARCHAR2(5), 
	"NVD_DSTATE" NVARCHAR2(32), 
	"NVD_USE" NVARCHAR2(50)
   ) ;
