--------------------------------------------------------
--  DDL for Table NVD_REGCHG
--------------------------------------------------------

  CREATE TABLE "SEN11CP2MSI164"."NVD_REGCHG" 
   (	"NVD_ZOBJNAME" NVARCHAR2(32), 
	"NVD_ZOBJDATE" NVARCHAR2(8), 
	"NVD_ZOBJTIME" NVARCHAR2(8), 
	"NVD_ZOBJRCRC" NVARCHAR2(8), 
	"NVD_ZOBJID" NVARCHAR2(12), 
	"NVD_ZUNUSED1" NVARCHAR2(4), 
	"NVD_ZOBJCID" NVARCHAR2(12), 
	"NVD_ZOBJRSIZ" NVARCHAR2(8), 
	"NVD_PATH" NVARCHAR2(255), 
	"NVD_VALUE" NVARCHAR2(255), 
	"NVD_NAME" NVARCHAR2(255), 
	"NVD_TYPE" NVARCHAR2(12), 
	"NVD_ZOBJPART" NVARCHAR2(128), 
	"NVD_REPORT" NVARCHAR2(5), 
	"NVD_DSTATE" NVARCHAR2(32), 
	"NVD_USE" NVARCHAR2(50)
   ) ;
