--------------------------------------------------------
--  DDL for Table NVD_SP
--------------------------------------------------------

  CREATE TABLE "SEN11CP2MSI164"."NVD_SP" 
   (	"NVD_ZOBJNAME" NVARCHAR2(32), 
	"NVD_ZOBJDATE" NVARCHAR2(8), 
	"NVD_ZOBJTIME" NVARCHAR2(8), 
	"NVD_ZOBJRCRC" NVARCHAR2(8), 
	"NVD_ZOBJID" NVARCHAR2(12), 
	"NVD_ZUNUSED1" NVARCHAR2(4), 
	"NVD_ZOBJCID" NVARCHAR2(12), 
	"NVD_ZOBJRSIZ" NVARCHAR2(8), 
	"NVD_NAME" NVARCHAR2(255), 
	"NVD_ID" NVARCHAR2(12), 
	"NVD_TAG" NVARCHAR2(255), 
	"NVD_POSTED" NVARCHAR2(18), 
	"NVD_REVISED" NVARCHAR2(18), 
	"NVD_SUPPORT" NVARCHAR2(1), 
	"NVD_URL" NVARCHAR2(255), 
	"NVD_FAQURL" NVARCHAR2(255), 
	"NVD_IMPACT" NVARCHAR2(8), 
	"NVD_PREREQ" NVARCHAR2(8), 
	"NVD_MITIGATE" NVARCHAR2(8), 
	"NVD_POPULAR" NVARCHAR2(8), 
	"NVD_CTIME" NVARCHAR2(24), 
	"NVD_MTIME" NVARCHAR2(24), 
	"NVD_OTYPE" NVARCHAR2(80), 
	"NVD_OASSERT" NVARCHAR2(255), 
	"NVD_OVERIFY" NVARCHAR2(255)
   ) ;
