--------------------------------------------------------
--  DDL for Table NVD_RELEASE
--------------------------------------------------------

  CREATE TABLE "SEN11CP2MSI164"."NVD_RELEASE" 
   (	"NVD_ZOBJNAME" NVARCHAR2(32), 
	"NVD_ZOBJDATE" NVARCHAR2(8), 
	"NVD_ZOBJTIME" NVARCHAR2(8), 
	"NVD_ZOBJRCRC" NVARCHAR2(8), 
	"NVD_ZOBJID" NVARCHAR2(12), 
	"NVD_ZUNUSED1" NVARCHAR2(4), 
	"NVD_ZOBJCID" NVARCHAR2(12), 
	"NVD_ZOBJRSIZ" NVARCHAR2(8), 
	"NVD_PRODUCT" NVARCHAR2(32), 
	"NVD_SP" NVARCHAR2(32), 
	"NVD_ID" NVARCHAR2(12), 
	"NVD_PROBE" NVARCHAR2(32), 
	"NVD_ARGS" NVARCHAR2(128), 
	"NVD_NAME" NVARCHAR2(255), 
	"NVD_CTIME" NVARCHAR2(24), 
	"NVD_MTIME" NVARCHAR2(24), 
	"NVD_PARENTC" NVARCHAR2(8), 
	"NVD_PARENTI" NVARCHAR2(32), 
	"NVD_CHILDC" NVARCHAR2(8), 
	"NVD_CHILDI" NVARCHAR2(32)
   ) ;
