--------------------------------------------------------
--  Constraints for Table NVD_DESTATUS
--------------------------------------------------------

  ALTER TABLE "SEN11CP2MSI164"."NVD_DESTATUS" MODIFY ("NVD_SCANTIME" NOT NULL ENABLE);
  ALTER TABLE "SEN11CP2MSI164"."NVD_DESTATUS" MODIFY ("NVD_PRODCNT" NOT NULL ENABLE);
  ALTER TABLE "SEN11CP2MSI164"."NVD_DESTATUS" MODIFY ("NVD_BULLCNT" NOT NULL ENABLE);
  ALTER TABLE "SEN11CP2MSI164"."NVD_DESTATUS" MODIFY ("NVD_OKBULL" NOT NULL ENABLE);
  ALTER TABLE "SEN11CP2MSI164"."NVD_DESTATUS" MODIFY ("NVD_WARNBULL" NOT NULL ENABLE);
  ALTER TABLE "SEN11CP2MSI164"."NVD_DESTATUS" MODIFY ("NVD_RPENBULL" NOT NULL ENABLE);
  ALTER TABLE "SEN11CP2MSI164"."NVD_DESTATUS" MODIFY ("NVD_ERRBULL" NOT NULL ENABLE);
  ALTER TABLE "SEN11CP2MSI164"."NVD_DESTATUS" MODIFY ("NVD_OTHRBULL" NOT NULL ENABLE);
  ALTER TABLE "SEN11CP2MSI164"."NVD_DESTATUS" MODIFY ("NVD_ZOBJRC" NOT NULL ENABLE);
  ALTER TABLE "SEN11CP2MSI164"."NVD_DESTATUS" ADD PRIMARY KEY ("NVD_ZOBJDEV")
  USING INDEX  ENABLE;
