--------------------------------------------------------
--  DDL for Table NVD_PACKAGE
--------------------------------------------------------

  CREATE TABLE "SEN11CP2MSI164"."NVD_PACKAGE" 
   (	"NVD_ZOBJNAME" NVARCHAR2(32), 
	"NVD_ZOBJDATE" NVARCHAR2(8), 
	"NVD_ZOBJTIME" NVARCHAR2(8), 
	"NVD_ZOBJRCRC" NVARCHAR2(8), 
	"NVD_ZOBJID" NVARCHAR2(12), 
	"NVD_ZUNUSED1" NVARCHAR2(4), 
	"NVD_ZOBJCID" NVARCHAR2(12), 
	"NVD_ZOBJRSIZ" NVARCHAR2(8), 
	"NVD_OWNER" NVARCHAR2(80), 
	"NVD_RELEASE" NVARCHAR2(80), 
	"NVD_ZSTOP000" NVARCHAR2(255), 
	"NVD_ZSTOP001" NVARCHAR2(255), 
	"NVD_ZSTOP002" NVARCHAR2(255), 
	"NVD_ZSTOP003" NVARCHAR2(255), 
	"NVD_PKGNAME" NVARCHAR2(80), 
	"NVD_NAME" NVARCHAR2(80), 
	"NVD_DESCRIPT" NVARCHAR2(255), 
	"NVD_SIZE" NVARCHAR2(12), 
	"NVD_COMPSIZE" NVARCHAR2(12), 
	"NVD_ITEMS" NVARCHAR2(7), 
	"NVD_PKGURL" NVARCHAR2(255), 
	"NVD_NOTES" NVARCHAR2(255)
   ) ;
