--------------------------------------------------------
--  DDL for Table NVD_PUBERROR
--------------------------------------------------------

  CREATE TABLE "SEN11CP2MSI164"."NVD_PUBERROR" 
   (	"NVD_ZOBJNAME" NVARCHAR2(32), 
	"NVD_ZOBJDATE" NVARCHAR2(8), 
	"NVD_ZOBJTIME" NVARCHAR2(8), 
	"NVD_ZOBJRCRC" NVARCHAR2(8), 
	"NVD_ZOBJID" NVARCHAR2(12), 
	"NVD_ZUNUSED1" NVARCHAR2(4), 
	"NVD_ZOBJCID" NVARCHAR2(12), 
	"NVD_ZOBJRSIZ" NVARCHAR2(8), 
	"NVD_URL" NVARCHAR2(255), 
	"NVD_PATCHNAM" NVARCHAR2(80), 
	"NVD_BULLETIN" NVARCHAR2(16), 
	"NVD_ERROR" NVARCHAR2(3), 
	"NVD_ERRORMSG" NVARCHAR2(255), 
	"NVD_ID" NVARCHAR2(32), 
	"NVD_LOCATION" NVARCHAR2(32), 
	"NVD_VENDOR" NVARCHAR2(80)
   ) ;
