--------------------------------------------------------
--  Constraints for Table NVD_BULLETIN
--------------------------------------------------------

  ALTER TABLE "SEN11CP2MSI164"."NVD_BULLETIN" MODIFY ("NVD_ZOBJNAME" NOT NULL ENABLE);
  ALTER TABLE "SEN11CP2MSI164"."NVD_BULLETIN" MODIFY ("NVD_ZOBJDATE" NOT NULL ENABLE);
  ALTER TABLE "SEN11CP2MSI164"."NVD_BULLETIN" MODIFY ("NVD_ZOBJTIME" NOT NULL ENABLE);
  ALTER TABLE "SEN11CP2MSI164"."NVD_BULLETIN" ADD PRIMARY KEY ("NVD_ZOBJNAME")
  USING INDEX  ENABLE;
