--------------------------------------------------------
--  DDL for Table OSMEVENTS
--------------------------------------------------------

  CREATE TABLE "SEN11CP2MSI164"."OSMEVENTS" 
   (	"EVENT_ID" NUMBER(*,0), 
	"DEPLOYMENT_ID" NVARCHAR2(100), 
	"DEVICE_ID" NVARCHAR2(50), 
	"SERIAL_NO" NVARCHAR2(100), 
	"ROMS_SERVER" NVARCHAR2(20), 
	"COMP_NAME" NVARCHAR2(100), 
	"EOS_NAME" NVARCHAR2(100), 
	"TOS_NAME" NVARCHAR2(100), 
	"IPADDRESS" NVARCHAR2(20), 
	"SUBNETMASK" NVARCHAR2(50), 
	"SUBNETID" NVARCHAR2(20), 
	"REGION" NVARCHAR2(100), 
	"JOBID" NVARCHAR2(100), 
	"EVENT_NAME" NVARCHAR2(30), 
	"EVENT_TYPE" NVARCHAR2(30), 
	"EVENT_SUBTYPE" NVARCHAR2(30), 
	"DRIVEMAP" NVARCHAR2(50), 
	"WITH_PBR" NVARCHAR2(10), 
	"TIMEZONE" NVARCHAR2(20), 
	"EVENT_TIME" DATE, 
	"DEP_STIME" DATE, 
	"DEP_ETIME" DATE, 
	"DURATION" NVARCHAR2(20), 
	"SUBEVENT" NVARCHAR2(200), 
	"STATUS" NVARCHAR2(50), 
	"PROGRESS_OVERALL" NVARCHAR2(10), 
	"ERRORMSG" NVARCHAR2(200)
   ) ;
